name: 'Setup Conda'
description: 'Create conda environment for GitHub Action Job'

runs:
  using: "composite"
  steps:
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: conda/conda-lock.yml
        environment-name: ICESat2-hackweek
        cache-environment: true
        cache-downloads: true
