# Edit this file to add dependencies to environment,
# Then run `./lock-environment.sh` to generate reproducible lock files

# !!! If you are developing the website locally use the existing lock files
# for your platform (`conda create --name hackweek --file conda-osx-64.lock`)
name: ICESat-2-hackweek
channels:
  - conda-forge
dependencies:
  ###----------------------------###
  ## Copy of CryoCloud (20230721) ##
  ###----------------------------###
  - python~=3.10.10
  # Required until https://github.com/jupyterhub/repo2docker/pull/1196 is merged
  - jupyterhub-singleuser>=3.0,<4.0
  # nbgitpuller is very helpful when distributing user content
  - nbgitpuller==1.1.1
  # Specify major version of jupyterlab to use. Manually bump it when you want to upgrade
  # jupyterlab version
  - jupyterlab>=3.0,<4.0
  # This provides memory usage stats on JupyterLab and classic notebook
  - jupyter-resource-usage==0.7.1
  # gh-scoped-creds allows users to securely push to GitHub from their repo.
  # https://blog.jupyter.org/securely-pushing-to-github-from-a-jupyterhub-3ee42dfdc54f has
  # some more information
  - gh-scoped-creds==4.1

  # Jupyter tools
  - ipython==8.6.0

  # Warning: There's a bug in ipykernel 6.18 that crashes hvplot.
  # See https://github.com/ipython/ipykernel/pull/1037. Restriction
  # can be relaxed once that's fixed.
  - ipykernel=6.16.0

  - ipywidgets==7.7.2
  - jupyterlab-favorites==3.1.0
  - jupyterlab-geojson==3.3.1
  - jupyterlab-git==0.41.0
  - jupyterlab-myst==1.1.0
  - jupyter-book==0.13.2
  - jupytext==1.14.1
  - nbconvert==6.5.3
  - nbdime==3.1.1

  # Core scientific python stack
  - cython==0.29.32 # optimization, C API access
  - hypothesis==6.58.0 # needed by numpy testing tools
  - networkx==2.8.8
  - numba==0.56.4 # high-performance numerics
  - numpy==1.23.5
  - pandas==1.5.2
  - scikit-image==0.19.3
  - scikit-learn==1.1.3
  - scipy==1.9.3
  - statsmodels==0.13.5
  - sympy==1.11.1
  - xarray>=2023.05.0

  # Visualization packages
  - bokeh==2.4.3
  - cartopy~=0.21.1 # geospatial plotting with matplotlib
  - geoviews==1.9.5
  - hvplot==0.8.2
  - ipyleaflet~=0.17.3
  - ipympl==0.9.2 # This enables matplotlib interaction with jupyter widgets
  - matplotlib==3.6.2
  - plotly==5.11.0
  - seaborn==0.12.1 # statistical plotting with matplotlib

  # Geospatial data packages
  - geopandas==0.12.1
  - rasterio~=1.3
  - rioxarray~=0.14.1
  - xarray-datatree~=0.0.12

  # File formats and file management, download, dataset caching
  - h5py~=3.8
  - hdf5~=1.14
  - h5netcdf==1.1.0
  - pooch==1.6.0

  # Cloud access tools and libraries
  - boto3
  - s3fs==2022.11.0
  # handle login and similar details for accessing earthdata protected data
  # https://github.com/nsidc/earthaccess
  - earthaccess==0.5.1
  # Access datasets exposed via STAC
  - pystac-client==0.5.1
  # Access datasets exposed via intake catalogs
  - intake==0.6.6
  - intake-esm==2022.9.18
  - intake-stac==0.4.0
  - intake-xarray==0.6.1

  # Distributed computing
  - dask==2022.11.0
  - dask-labextension==6.0.0

  # Other useful generic python packages
  - pillow~=9.5 # Python imaging library, useful for many image-related tasks
  - pytest==7.2.0
  - pytest-cov==4.0.0
  - pep8==1.7.1
  - flake8==5.0.4
  - tqdm==4.64.1 # progress bars, with notebook support

  # Packages specific to cryo work
  - icepyx==0.7.0
  - sliderule~=3.5.0

  # Command line tools
  - git

  ###---------------------------###
  ## UW Hackweek website section ##
  ###---------------------------###
  # Website/Splashpage
  - cookiecutter
  # Dependencies of jinja-markdown:
  - jinja2>=2.11
  - pygments>=2.6.1
  - pymdown-extensions>=7.1
  - pip:
    - jinja-markdown==1.210911
platforms:
  - linux-64
  - osx-64
  - osx-arm64
